services:
  # Redis for caching
  redis:
    image: redis:7-alpine
    container_name: moodflix-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - moodflix-network

  # Backend API service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: moodflix-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=${FLASK_ENV:-production}
      - FLASK_DEBUG=${FLASK_DEBUG:-false}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TMDB_API_KEY=${TMDB_API_KEY}
      - REDIS_URL=redis://redis:6379/0
      - RATE_LIMIT_ENABLED=${RATE_LIMIT_ENABLED:-true}
      - RATE_LIMIT_PER_MINUTE=${RATE_LIMIT_PER_MINUTE:-3}
      - RATE_LIMIT_PER_DAY=${RATE_LIMIT_PER_DAY:-100}
      - OPENAI_MONTHLY_LIMIT=${OPENAI_MONTHLY_LIMIT:-7}
      - EMERGENCY_STOP=${EMERGENCY_STOP:-false}
      - CACHE_TTL_HOURS=${CACHE_TTL_HOURS:-24}
    volumes:
      - ./backend:/app
      - backend_logs:/app/logs
    depends_on:
      - redis
    networks:
      - moodflix-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: moodflix-frontend
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      - REACT_APP_API_BASE_URL=${REACT_APP_API_BASE_URL:-http://localhost:5000}
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - moodflix-network

  # Nginx reverse proxy (optional for production)
  nginx:
    image: nginx:alpine
    container_name: moodflix-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - nginx_logs:/var/log/nginx
    depends_on:
      - frontend
      - backend
    networks:
      - moodflix-network
    profiles:
      - production

volumes:
  redis_data:
    driver: local
  backend_logs:
    driver: local
  nginx_logs:
    driver: local

networks:
  moodflix-network:
    driver: bridge

